version: '3'

services:
  web:
    build: .
    image: fpa-web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./mysite:/code
    ports:
      - "8000:8000"
    depends_on:
      - web-migration
  web-migration:
    build: .
    image: fpa-web
    command: python3 manage.py migrate
    volumes:
      - ./mysite:/code
