# Generated by Django 2.0.1 on 2018-01-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_text', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(verbose_name='plan to begin')),
                ('end_date', models.DateTimeField(verbose_name='plan to end')),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
