# Generated by Django 2.0.1 on 2018-01-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='remark',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
