# Generated by Django 2.0.1 on 2018-01-13 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_plan_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
