# Generated by Django 2.0.1 on 2018-01-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_auto_20180113_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_time', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan')),
            ],
            options={
                'db_table': 'plans_plan_change_log',
            },
        ),
    ]
