# Generated by Django 2.0.1 on 2018-01-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0010_planchange_change_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('U', 'Not Start'), ('I', 'In Progress'), ('F', 'Finished')], default='U', max_length=1),
        ),
    ]
