# Generated by Django 2.0.1 on 2018-01-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perioddef',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
